GET http://localhost:5000/pegawai

###
GET http://localhost:5000/pegawai/12345

###
POST http://localhost:5000/pegawai
Content-Type: application/json

{
    "name": "robi",
    "id": "32145",
    "ttl": "Balam, 17-10-1912",
    "jeniskelamin": "Pria",
    "divisi": "Produksi",
    "agama": "Islam",
    "alamat": "Jl.Pangeran Senopati Raya, Balam",
    "telepon": "081234567890",
    "email": "robi.32145@email.com",
    "username": "robi321",
    "password": "12345",
    "tipeakun": "user"
}

###
PATCH  http://localhost:5000/pegawai/12345
Content-Type: application/json

{
    "name": "robi",
    "id": "32145",
    "ttl": "Balam, 17-10-1912",
    "jeniskelamin": "Pria",
    "divisi": "Produksi",
    "agama": "Islam",
    "alamat": "Jl.Pangeran Senopati Raya, Balam",
    "telepon": "081234567890",
    "email": "robi.32145@email.com",
    "username": "robi321",
    "password": "12345",
    "tipeakun": "user"
}

###
DELETE  http://localhost:5000/pegawai/54321

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "akbarbarbar",
    "password": "09876"
}

###
GET http://localhost:5000/validate-token
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrYmFyMjAwMSIsInRpcGVha3VuIjoidXNlciIsImlhdCI6MTY2NzE5NTg1MX0.nLtae5LOnh_RroMSu-PJWUiOoifw7UPwMw6-plyxeTo


###
POST http://localhost:5000/suratCuti
Content-Type: application/json

{
    "name": "maulana",
    "userid": "12345",
    "divisi": "Produksi",
    "jatahcuti": "25 Hari",
    "tglpengajuan": "2022-11-12",
    "tglmulai": "2022-12-13",
    "tglselesai": "2022-12-17",
    "jeniscuti": "Cuti Tahunan",
    "alasan": "Sakit",
    "status": "Sedang Diproses"
}

###
GET http://localhost:5000/suratCuti/pegawai/12345

###
DELETE  http://localhost:5000/suratCuti/1

###
POST http://localhost:5000/admin
Content-Type: application/json

{
    "name": "widodo",
    "id": "09876",
    "ttl": "Balam, 17-01-2001",
    "jeniskelamin": "Pria",
    "divisi": "Produksi",
    "agama": "Islam",
    "alamat": "Jl.Belwis, Lampung Selatan",
    "telepon": "080987654321",
    "email": "widodo.09876@email.com",
    "username": "widodo098",
    "password": "12345",
    "tipeakun": "admin"
}

###
DELETE  http://localhost:5000/admin/09876

###
GET  http://localhost:5000/pegawai-per-divisi/Produksi

###
GET  http://localhost:5000/admin/09876